services:
  - type: web
    name: solar-anomaly-pipeline
    env: python
    buildCommand: pip install -r PipeLine/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir PipeLine app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
